swagger: '2.0'
info:
  title: Viajes
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json

paths:
  
  /airports:
    get:
      tags:
        - aiports
      summary: get all aiports of the world!
      x-swagger-router-controller: aiports
      responses:
        '200':
          description: airports list
          schema:
            $ref: '#/definitions/aiport'
            
  /countries:
    get:
      tags:
        - countries
      summary: get all countries of the world!
      x-swagger-router-controller: countries
      responses:
        '200':
          description: countries list
          schema:
            $ref: '#/definitions/country'
            
  /states:
    get:
      tags:
        - states
      summary: get all states
      x-swagger-router-controller: states
      responses:
        '200':
          description: states list
          schema:
            $ref: '#/definitions/state'
          
definitions:

  aiport:
    type: object
    properties:
      iata:
        type: string
      lon:
        type: string
      iso:
        type: string
      status:
        type: number
      name:
        type: string
      continent:
        type: string
      type:
        type: string
      lat:  
        type: number
      size:
        type: string
        
  country:
    type: object
    properties:
      name:
        type: string
      code:
        type: string
      continent:
        type: string
      filename:
        type: string
  
  state:
    type: object
    properties:
      name:
        type: string
      code:
        type: string
    
        

    
    
            
  
